name: Build and Release Fyne App

on:
  push:
    tags:
      - 'v*'  # Runs only when a version tag is pushed (e.g., v1.0.0)

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build & Package
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            fyne package -os windows -output docker-dashboard-windows.exe
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            fyne package -os darwin -output docker-dashboard-macos.app
          else
            fyne package -os linux -output docker-dashboard-linux
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-dashboard-${{ matrix.os }}
          path: docker-dashboard-*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
